version: '3.8'

networks:
  k6:
  grafana:

services:
  jenkins:
    container_name: jenkins
    build: .
    networks:
      - k6
      - grafana
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.8
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  influxdb:
    container_name: influxDB
    image: influxdb:1.8
    networks:
      - grafana
      - k6
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6